### ISSUE TITLE
Lookup fail for "rmi:" since requests goes through "NamingContext"

### ISSUE THREAD

**Issue by lasanthaS** [wso2/carbon-jndi#43]
**Description:**
When lookup happens for "rmi" context, the following exception occurs.

```log
IOException: java.io.IOException: Failed to retrieve RMIServer stub: javax.naming.NameNotFoundException: Name [rmi://localhost:10000/jmxrmi] is not bound in this Context. Unable to find [rmi:].
    at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:369)
    at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270)
    ...
Caused by: javax.naming.NameNotFoundException: Name [rmi://localhost:10000/jmxrmi] is not bound in this Context. Unable to find [rmi:].
    at org.wso2.carbon.jndi.internal.impl.NamingContext.lookup(NamingContext.java:754)
    at org.wso2.carbon.jndi.internal.impl.NamingContext.lookup(NamingContext.java:142)
    at org.wso2.carbon.jndi.internal.osgi.WrapperContext.lookup(WrapperContext.java:118)
    at javax.naming.InitialContext.lookup(InitialContext.java:417)
    at javax.management.remote.rmi.RMIConnector.findRMIServerJNDI(RMIConnector.java:1955)
    at javax.management.remote.rmi.RMIConnector.findRMIServer(RMIConnector.java:1922)
    at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:287)
    ... 26 more
```

"rmi:" is available in the "InitialContext", but since the "NamingContext" is set as the default initial context "rmi:" does not get resolved.

**Comment by lasanthaS** [comment]
Resolved from the above PR, hence closing
